//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KYKY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDKYKYEntities : DbContext
    {
        private static BDKYKYEntities _context;    
        
        public BDKYKYEntities()
            : base("name=BDKYKYEntities")
        {
        }
    
        public static BDKYKYEntities GetContext()
        {
            if(_context == null)
                _context = new BDKYKYEntities();

                return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Polzovat> Polzovat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Dir> Dir { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<stud> stud { get; set; }
    }
}
